#!/usr/bin/env python3
"""Record the Streamlit demo with Playwright.

Part 1 (version-aware): reset, upload demo/docs/demo_policy_v1.md then v2,
show the graph, ask about a changed clause, show the review queue.
Part 2 (permission-aware): ingest the fictional Acme policy (HR-only sections
are marked in the file), ask the same question as employee and as hr, then
show the audit log.

Answers are generated by Gemini. The key comes only from the local .env
(GEMINI_API_KEY), which the app loads itself; this script never prints or
writes it, and redacts it from any error message. KB_OFFLINE=1 is still set
so the embedding and NLI backends are the offline ones, same as before, and
the ingest outcomes don't change. Gemini can be slow, so each answer gets up
to 30s per attempt, and the waiting time is cut out of the final video (with
a caption saying so).

Every step checks what is actually on screen and raises if it isn't there,
so a blank or broken tab is never recorded as if it worked. If the final
video comes out longer than MAX_LEN (slow page loads), it records again.

Outputs (git-ignored): demo/raw/demo_raw.webm and demo/raw/captions.json.

    python demo/record_demo.py
"""

import json
import os
import re
import shutil
import subprocess
import sys
import time
import urllib.request
from pathlib import Path

from dotenv import dotenv_values
from playwright.sync_api import sync_playwright, expect

ROOT = Path(__file__).resolve().parent.parent
DEMO = ROOT / "demo"
RAW = DEMO / "raw"
STORAGE = DEMO / ".storage"
PORT = 8599
URL = f"http://localhost:{PORT}"
DOC_ID = "alder_ridge_security"
VERSION_Q = "How often must passwords be changed?"
ACCESS_Q = "What are the engineer salary bands?"
SALARY_RE = re.compile(r"65[,.\s]?000|65k", re.I)
SALARY_TOP_RE = re.compile(r"90[,.\s]?000|90k", re.I)
# Facts that only appear in acme sections an employee may not see (salary
# bands, bonus %, hiring limit, review cycle, disciplinary records). Taken by
# hand from data/acme_policy_v2.md. If Gemini says any of these to an
# employee, something it shouldn't have got reached it.
RESTRICTED_FACTS = [SALARY_RE, SALARY_TOP_RE, re.compile(r"\b8\s?%"),
                    re.compile(r"4 new staff", re.I), re.compile(r"twice per year", re.I),
                    re.compile(r"disciplinary records? (are|is)? ?(kept|on file)", re.I)]
ANSWER_WAIT_MS = 30_000
ASK_ATTEMPTS = 3
MAX_LEN = 78.0
ATTEMPTS = 3

captions: list[dict] = []
cuts: list[list[float]] = []
t0 = 0.0


def gemini_key() -> str:
    return dotenv_values(ROOT / ".env").get("GEMINI_API_KEY") or os.environ.get("GEMINI_API_KEY", "")


def now() -> float:
    return time.time() - t0


def caption(text: str, hold: float):
    """Show a caption for `hold` seconds of video time (also blocks for that long)."""
    start = now()
    captions.append({"start": round(start, 2), "end": round(start + hold, 2), "text": text})
    time.sleep(hold)


def during(text: str):
    """Caption that covers an action instead of a pause. Call the returned
    function when the action is done."""
    cap = {"start": round(now(), 2), "end": None, "text": text}
    captions.append(cap)

    def done(extra: float = 0.0):
        cap["end"] = round(now() + extra, 2)
    return done


def start_server() -> subprocess.Popen:
    shutil.rmtree(STORAGE, ignore_errors=True)
    # The key is not passed here: the app's own load_dotenv() reads .env from
    # the project root. Only make sure nothing in this shell blanks it out,
    # since load_dotenv doesn't override a variable that is already set.
    env = {k: v for k, v in os.environ.items() if k not in ("GEMINI_API_KEY", "GOOGLE_API_KEY")}
    env.update({"KB_STORAGE_DIR": str(STORAGE), "KB_OFFLINE": "1"})
    proc = subprocess.Popen(
        [sys.executable, "-m", "streamlit", "run", "app.py",
         "--server.port", str(PORT), "--server.headless", "true",
         "--browser.gatherUsageStats", "false"],
        cwd=ROOT, env=env, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )
    for _ in range(120):
        try:
            if urllib.request.urlopen(f"{URL}/_stcore/health", timeout=1).status == 200:
                return proc
        except Exception:
            time.sleep(1)
    stop_server(proc)
    raise RuntimeError("Streamlit did not become ready in 120s")


def stop_server(proc: subprocess.Popen):
    if sys.platform == "win32":
        subprocess.run(["taskkill", "/PID", str(proc.pid), "/T", "/F"],
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    else:
        proc.terminate()


def wait_ready(page, attempts: int = 3):
    """Wait for the app shell. Streamlit occasionally loads a page whose sidebar
    never appears; a reload fixes that, so retry before giving up."""
    for attempt in range(attempts):
        try:
            expect(page.get_by_text("Ingest a document version")).to_be_visible(timeout=40_000)
            expect(page.get_by_role("button", name="Reset knowledge base")).to_be_visible(timeout=20_000)
            return
        except AssertionError:
            if attempt == attempts - 1:
                raise
            page.reload()


def idle(page):
    """Wait until Streamlit is not mid-rerun (its status widget shows 'Stop' while running)."""
    expect(page.get_by_text("Stop", exact=True)).to_have_count(0, timeout=120_000)
    page.wait_for_timeout(300)


def rerun(page):
    """Streamlit's 'r' shortcut. Keeps the sidebar selection, unlike a reload,
    and redraws the sidebar counters (they're drawn before ingest runs)."""
    page.mouse.click(1100, 690)  # empty spot, so the key isn't typed into a field
    page.keyboard.press("r")
    page.wait_for_timeout(400)
    idle(page)


def set_field(page, label: str, value: str):
    box = page.get_by_label(label, exact=True)
    box.fill(value)
    box.press("Enter")
    page.wait_for_timeout(300)


def pick(scope, page, label: str, value: str):
    """Choose `value` in a Streamlit selectbox."""
    box = scope.get_by_role("combobox", name=label)
    option = page.get_by_role("option", name=value, exact=True)
    # the dropdown sometimes doesn't open on the first click (focus is still
    # somewhere else after a rerun), so try a few times
    for _ in range(4):
        box.click()
        try:
            expect(option).to_be_visible(timeout=3_000)
            break
        except AssertionError:
            page.keyboard.press("Escape")
            page.wait_for_timeout(300)
    option.click()
    idle(page)
    expect(box).to_have_value(value)


def viewer(page, tenant: str, role: str):
    sb = page.get_by_test_id("stSidebar")
    pick(sb, page, "Tenant", tenant)
    pick(sb, page, "Role", role)
    expect(sb.get_by_label("User name", exact=True)).to_have_value(f"demo-{role}")


def metrics(page) -> dict:
    """{label: value} for every st.metric in the main area."""
    out = {}
    for m in page.get_by_test_id("stMain").get_by_test_id("stMetric").all():
        label = m.get_by_test_id("stMetricLabel").inner_text().strip()
        out[label] = m.get_by_test_id("stMetricValue").inner_text().strip()
    return out


def check_metrics(page, want: dict):
    got = metrics(page)
    for k, v in want.items():
        if got.get(k) != str(v):
            raise RuntimeError(f"ingest metrics: expected {k}={v}, got {got}")


def run_ingest(page):
    page.get_by_role("button", name="Ingest", exact=True).click()
    expect(page.get_by_text("Duplicates skipped")).to_be_visible(timeout=120_000)
    idle(page)
    page.get_by_text("Duplicates skipped").scroll_into_view_if_needed()


def upload(page, version: str, date: str):
    f = DEMO / "docs" / f"demo_policy_{version}.md"
    page.get_by_role("tab", name="Ingest").click()
    idle(page)
    # scoped to the uploader: the roles multiselect also has a "Remove all"
    for rm in page.get_by_test_id("stFileUploader").get_by_role("button", name="Remove ").all():
        rm.click()  # single-file uploader: drop the previous version first
        idle(page)
    page.locator('input[type="file"]').set_input_files(str(f))
    expect(page.get_by_text(f.name)).to_be_visible(timeout=30_000)
    idle(page)
    set_field(page, "Document ID", DOC_ID)
    set_field(page, "Version", version)
    set_field(page, "Effective date", date)
    expect(page.get_by_role("textbox", name="Tenant")).to_have_value("default")
    run_ingest(page)


def type_question(page, question: str, typed: bool):
    page.get_by_role("tab", name="Ask").click()
    q = page.get_by_label("Question", exact=True)
    if q.input_value() != question:
        q.fill("")
        q.click()
        if typed:
            page.keyboard.type(question, delay=35)
        else:
            q.fill(question)
        q.press("Enter")
        idle(page)


def ask(page, question: str, typed: bool, tenant: str, role: str, done=None):
    """Ask and wait for Gemini. `done` ends the action caption at the click.
    Returns (panel text, answer text, generator label)."""
    type_question(page, question, typed)
    if done:
        done()
    asked = None
    for attempt in range(1, ASK_ATTEMPTS + 1):
        page.get_by_role("button", name="Ask", exact=True).click()
        asked = asked or now()
        try:
            expect(page.get_by_text("Answer", exact=True)).to_be_visible(timeout=ANSWER_WAIT_MS)
            expect(page.get_by_text("Stop", exact=True)).to_have_count(0, timeout=ANSWER_WAIT_MS)
            break
        except AssertionError:
            if attempt == ASK_ATTEMPTS:
                raise RuntimeError(f"no answer after {ASK_ATTEMPTS} tries of {ANSWER_WAIT_MS // 1000}s")
            print(f"  answer slow (try {attempt}), reloading and asking again")
            page.reload()  # a reload drops the sidebar choice, so set it again
            wait_ready(page)
            viewer(page, tenant, role)
            type_question(page, question, typed=False)
    answered = now()
    page.wait_for_timeout(300)
    # keep ~1.5s of the spinner, cut the rest in build_video.py
    if answered - asked > 2.5:
        cuts.append([asked + 1.5, answered - 0.3])
        captions.append({"start": round(asked, 2), "end": round(asked + 1.5, 2),
                         "text": f"Waiting for Gemini ({answered - asked:.0f}s, shortened in the video)"})
    panel = page.get_by_role("tabpanel", name="Ask").inner_text()
    answer = panel.split("Answer", 1)[1].split("generated by", 1)[0]
    generator = panel.split("generated by", 1)[1].split("\n", 1)[0].strip()
    # query.py falls back to "extractive" when the LLM call fails. That must
    # not be recorded as if Gemini had answered.
    if "gemini" not in generator.lower() or "extractive" in answer:
        raise RuntimeError(f"Ask tab is not showing a Gemini answer (generator={generator!r})")
    return panel, answer, generator


def open_detail(page) -> str:
    page.get_by_text("Retrieval detail").click()
    expect(page.get_by_text("Filtered out", exact=True)).to_be_visible()
    page.mouse.move(800, 400)
    page.mouse.wheel(0, 380)  # bring the detail above the caption bar
    page.wait_for_timeout(400)
    return page.get_by_role("tabpanel", name="Ask").inner_text()


def record() -> float:
    global t0
    captions.clear()
    RAW.mkdir(exist_ok=True)
    for old in RAW.glob("*.webm"):
        old.unlink()
    server = start_server()
    try:
        with sync_playwright() as pw:
            browser = pw.chromium.launch()
            # Warm-up context (not recorded): load the KB once so the
            # recorded session does not show a start-up spinner.
            warm = browser.new_context(viewport={"width": 1280, "height": 720})
            wp = warm.new_page()
            wp.goto(URL)
            wait_ready(wp)
            warm.close()

            ctx = browser.new_context(
                viewport={"width": 1280, "height": 720},
                record_video_dir=str(RAW),
                record_video_size={"width": 1280, "height": 720},
            )
            page = ctx.new_page()
            t0 = time.time()
            page.goto(URL)
            wait_ready(page)
            trim = max(now() - 0.3, 0.0)  # drop the page-load lead-in from the final cut

            # ================= part 1: version-aware retrieval
            viewer(page, "default", "employee")
            page.get_by_role("button", name="Reset knowledge base").click()
            wait_ready(page)
            idle(page)
            expect(page.get_by_test_id("stSidebar").get_by_text("Active").first).to_be_visible()
            # the key field must stay masked; check it's filled without reading it out
            key_box = page.get_by_test_id("stSidebar").get_by_role("textbox", name="Gemini API Key (free)")
            expect(key_box).to_have_attribute("type", "password")
            if not key_box.input_value():
                raise RuntimeError("the app did not load GEMINI_API_KEY from .env")
            caption("Fictional documents, answers generated by Gemini. Part 1: version-aware retrieval", 3.0)

            done = during("Upload policy v1 (fictional security policy)")
            upload(page, "v1", "2024-01-15")
            done()
            check_metrics(page, {"Chunks": 8, "Inserted": 8, "Superseded": 0})
            caption("Policy v1 ingested: 8 clauses inserted", 3.0)

            page.evaluate("window.scrollTo(0, 0)")
            done = during("Upload policy v2 of the same document")
            upload(page, "v2", "2026-01-15")
            done()
            check_metrics(page, {"Chunks": 9, "Inserted": 1, "Superseded": 3, "Duplicates skipped": 3})
            expect(page.get_by_text("2 conflict(s) routed to human review.")).to_be_visible()
            caption("v2 contradicts v1 in 3 clauses, so the old ones are marked superseded", 3.5)
            caption("1 new clause inserted, 3 unchanged skipped, 2 unclear changes sent to review", 3.5)

            rerun(page)
            sb = page.get_by_test_id("stSidebar")
            expect(sb.get_by_test_id("stMetric").filter(has_text="Superseded")).to_contain_text("3")

            page.get_by_role("tab", name="Knowledge graph").click()
            expect(page.get_by_text("Audit trail")).to_be_visible(timeout=30_000)
            expect(page.locator("svg g.node")).to_have_count(14, timeout=30_000)
            expect(page.locator("svg g.edge")).to_have_count(3)
            caption("Knowledge graph: each red SUPERSEDES edge points from v2 to the v1 clause it replaced", 4.5)

            done = during("Ask about a clause that changed (password rotation)")
            panel, answer, gen1 = ask(page, VERSION_Q, True, "default", "employee", done)
            if "180" not in answer or re.search(r"\b90 days", answer):
                raise RuntimeError(f"answer should use the v2 rule (180 days): {answer!r}")
            caption("Gemini answers from the active clauses only: every 180 days (v2)", 3.5)
            detail = open_detail(page)
            filtered = detail.split("Filtered out", 1)[1]
            if "1.1 Password Rotation" not in filtered or "SUPERSEDED" not in filtered:
                raise RuntimeError(f"superseded v1 clause not listed as filtered out: {filtered!r}")
            caption("The old v1 clause (90 days) is listed as filtered out, it never reached the answer", 4.0)

            page.get_by_role("tab", name="Review queue").click()
            expect(page.get_by_text("Existing (still active)")).to_have_count(2, timeout=30_000)
            assert page.get_by_text("Queue is empty.").count() == 0
            caption("Review queue: unclear changes wait for a person, the old rule stays active", 4.0)

            # ================= part 2: permission-aware retrieval
            page.evaluate("window.scrollTo(0, 0)")
            done = during("Part 2, permission-aware retrieval: sidebar set to tenant acme, role employee")
            viewer(page, "acme", "employee")
            done(0.8)
            time.sleep(0.8)
            done = during("Ingest Acme's policy (fictional), HR-only sections are marked in the file")
            page.get_by_role("tab", name="Ingest").click()
            pick(page.get_by_test_id("stMain"), page, "Bundled document", "acme_policy_v2.md")
            set_field(page, "Document ID", "people_policy")
            expect(page.get_by_role("textbox", name="Tenant")).to_have_value("acme")
            run_ingest(page)
            check_metrics(page, {"Chunks": 8, "Inserted": 8})
            done(1.5)
            time.sleep(1.5)

            done = during("Employee asks about salary bands (an HR-only clause)")
            panel, answer, gen2 = ask(page, ACCESS_Q, True, "acme", "employee", done)
            leaked = [r.pattern for r in RESTRICTED_FACTS if r.search(answer)]
            if leaked or "4.1 Salary Bands" in panel:
                raise RuntimeError(f"employee answer contains restricted text: {leaked}")
            employee_answer = answer
            caption("Role employee: salary bands are not retrieved, so Gemini can't state them", 3.5)
            detail = open_detail(page)
            m = re.search(r"(\d+) nearby chunk\(s\) hidden by permissions", detail)
            if not m or int(m.group(1)) == 0 or SALARY_RE.search(detail):
                raise RuntimeError(f"expected a hidden-by-permissions count and no salary text: {detail!r}")
            caption(f"Filtered inside the vector search, before Gemini: {m.group(1)} chunks hidden", 3.5)

            page.evaluate("window.scrollTo(0, 0)")
            done = during("Switch the role to hr in the sidebar and ask again")
            viewer(page, "acme", "hr")
            time.sleep(1.2)  # let the role change be read before the answer appears
            panel, answer, gen3 = ask(page, ACCESS_Q, False, "acme", "hr", done)
            if not (SALARY_RE.search(answer) and SALARY_TOP_RE.search(answer)):
                raise RuntimeError(f"hr should get the salary bands: {answer!r}")
            caption("Same question as role hr: the clause is retrieved and Gemini states the bands", 3.5)

            page.get_by_role("tab", name="Audit log").click()
            audit = page.get_by_role("tabpanel", name="Audit log")
            expect(audit.get_by_test_id("stDataFrame")).to_be_visible(timeout=30_000)
            rows = [json.loads(x) for x in (STORAGE / "audit_log.jsonl").read_text(encoding="utf-8").splitlines()]
            acme = [(r["user"], r["role"], r["query"]) for r in rows if r["tenant"] == "acme"]
            # a slow-answer retry asks again, and that is logged too, so
            # collapse repeats before comparing
            distinct = [r for i, r in enumerate(acme) if i == 0 or acme[i - 1] != r]
            if distinct != [("demo-employee", "employee", ACCESS_Q), ("demo-hr", "hr", ACCESS_Q)]:
                raise RuntimeError(f"audit log does not hold the two acme queries: {acme}")
            # the retrieved ids are exactly the chunks whose text went into the
            # Gemini prompt; none may be one the employee can't see
            restricted = restricted_acme_ids()
            sent = set()
            for r in rows:
                if r["tenant"] == "acme" and r["role"] == "employee":
                    sent |= set(r["retrieved"]) & restricted
            if sent:
                raise RuntimeError(f"restricted chunks were sent to Gemini for the employee: {sent}")
            # the grid is drawn on a canvas, but it keeps an offscreen <table>
            # copy of the cells for screen readers; check what is displayed
            cells = audit.get_by_test_id("stDataFrame").locator("table").text_content()
            for want in ("demo-employee", "demo-hr", ACCESS_Q):
                if want not in cells:
                    raise RuntimeError(f"audit tab does not show {want!r}: {cells[:300]!r}")
            extra = "" if len(acme) == 2 else f" ({len(acme)} rows, slow-answer retries included)"
            caption(f"Audit log: both queries recorded with user, role and chunk ids{extra}", 4.0)

            ctx.close()  # flushes the video
            browser.close()
        vids = sorted(RAW.glob("*.webm"), key=lambda p: p.stat().st_mtime)
        final = RAW / "demo_raw.webm"
        if final.exists():
            final.unlink()
        vids[-1].rename(final)
        caps = [{**c, "start": round(c["start"] - trim, 2), "end": round(c["end"] - trim, 2)}
                for c in captions]
        cut_list = [[round(a - trim, 2), round(b - trim, 2)] for a, b in cuts]
        (RAW / "captions.json").write_text(json.dumps(
            {"trim": round(trim, 2), "cuts": cut_list, "captions": caps}, indent=2), encoding="utf-8")
        length = max(c["end"] for c in caps) + 0.5 - sum(b - a for a, b in cut_list)
        print(f"Recorded {final}: {length:.1f}s after trim and cuts, {len(caps)} captions")
        print(f"generator labels: part 1 {gen1!r}, employee {gen2!r}, hr {gen3!r}")
        print(f"employee answer: {employee_answer.strip()!r}")
        return length
    finally:
        stop_server(server)


def restricted_acme_ids() -> set[str]:
    sys.path.insert(0, str(ROOT))
    from src.chunking import chunk_file
    chunks = chunk_file(ROOT / "data" / "acme_policy_v2.md", "people_policy", "v2",
                        "2026-01-15", tenant_id="acme")
    return {c.id for c in chunks if not ({"all", "employee"} & set(c.allowed_roles))}


def main():
    key = gemini_key()
    if not key:
        raise SystemExit("GEMINI_API_KEY not found in .env")
    try:
        for attempt in range(1, ATTEMPTS + 1):
            cuts.clear()
            length = record()
            if length <= MAX_LEN:
                return
            print(f"attempt {attempt}: {length:.1f}s is over {MAX_LEN}s, recording again")
        raise SystemExit(f"still over {MAX_LEN}s after {ATTEMPTS} attempts")
    except Exception as exc:
        # playwright errors can include page snapshots; never echo the key
        msg = f"{type(exc).__name__}: {exc}".replace(key, "[redacted]")
        raise SystemExit(f"recording failed: {msg}") from None


if __name__ == "__main__":
    main()
